name: Player Logger Plugin
version: '1.0'
main: me.matt5262.playerLoggerPlugin.PlayerLoggerPlugin
api-version: '1.21'
authors: [ Matt_5262 ]
description: Its supposed to log player stuff
website: https://discord.com/invite/JdzQMaNmKw
